# Generated by Django 6.0.2 on 2026-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_enrollment_unique_together_enrollment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='max_units',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('WAITLISTED', 'Waitlisted')], default='ENROLLED', max_length=10),
        ),
    ]
